### ISSUE TITLE
Actividad 2

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-team-project-ra#1]
[APLICACIÓN WEB CON RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-team-project-ra/files/10815802/APLICACION.WEB.CON.RA.pdf)

**Comment by kirus21** [comment]
18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
